### ISSUE TITLE
Modify snapshots to clearly declare that they were not created by wikipedia

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#13]
If we publish unmodified snapshots of wikipedia it may confuse visitors, leading them to believe that the snapshots were published by Wikipedia or by volunteers who contribute to WIkipedia in Turkey. This could present a real risk for those volunteers, who have nothing to do with our snapshots, and may harm wikipedia, who did not ask us to do this.

I propose modifying the snapshots to: 

1. Remove references to the Wikimedia user group in Turkey from the bottom of the page

2. Adjust the top of the page to distinguish it from Wikipedia (by removing the puzzle globe logo and adding a prominent explanation that this is an independent project, not affiliated with Wikipedia)

This will force us to scrap all of the snapshots we've built and start over with modified code, which will delay the release of the snapshots by at least a few days.

**Comment by jbenet** [comment]
## top of the page

Maybe the logo could be derived. the logo is Creative Commons, so probably fine.

### IPFS Shields Wikipedia

![wikipedia-on-ipfs](https://cloud.githubusercontent.com/assets/138401/25736516/2de732c2-3127-11e7-889e-e981cce93ebf.jpg)

**Comment by jbenet** [comment]
## bottom of the page

- we should remove the whole WMTR social media section there-- it's actually pulling from upload.wikimedia.org apparently.
- we should add our own section there with:
  - links to download IPFS -- ipfs should be included as part of the archive root, so that it can self-replicate...
  - our own social media things that _share_ the IPFS link to that page to twitter, fb, etc.
- also:
  - snapshot creation information (when it was created, at least. probably shouldn't say by whom.)
  - disclaimer about not being affiliated.

Maybe something like

![footer](https://cloud.githubusercontent.com/assets/138401/25736492/0dd9bb6c-3127-11e7-922a-0f69427b0da4.jpg)

Move the legal disclaimer to the bottom, add to it, and add snapshot info. (maybe can grab the hash from addr bar and include it with js for info and links...)

> This article is issued from Vikipedi - version of the 3/17/2016. The text is available under the Creative Commons Attribution/Share Alike but additional terms may apply for the media files. The Distributed Wikipedia Project is not affiliated to Wikipedia in any way.
>
> **From Snapshot:** /ipfs/QmQP99yW82xNKPxXLroxj1rMYMGF6Grwjj2o4svsdmGh7S
> **Created on:** 2017-05-05
> **IPFS Link:** dweb://ipfs/QmQP99yW82xNKPxXLroxj1rMYMGF6Grwjj2o4svsdmGh7S/out/A/Anasayfa.html
> **HTTP Link:** https://ipfs.io/ipfs/QmQP99yW82xNKPxXLroxj1rMYMGF6Grwjj2o4svsdmGh7S/out/A/Anasayfa.html
> [Download IPFS v0.4.8 Here](/ipfs/<dist-hash>/v0.4.8)

**Comment by jbenet** [comment]
(used wikipedia font "Linux Libertine")

**Comment by jbenet** [comment]
@whyrusleeping was worried this may require regenerating everything. I think we may be able to circumvent that by:
- changing the header image
- writing a program that modifies the footer of every page
- re-add to ipfs

**Comment by flyingzumwalt** [comment]
let's add these things to the [distributed-wikipedia repo](https://github.com/ipfs/distributed-wikipedia):
- [ ] an html file with the modified footer @jbenet proposed in https://github.com/ipfs/distributed-wikipedia/issues/13#issuecomment-299398457
- [ ] the logo @jbenet proposed in https://github.com/ipfs/distributed-wikipedia/issues/13#issuecomment-299398452 
- [ ] the script that 
    - changes the header image
    - modifies the footer of every page

**Comment by flyingzumwalt** [comment]
Instead of saying
> This article is issued from Vikipedi  

it should say 

> This page was generated and distributed by the Distributed Wikipedia project. It's based on the article  issued from Vikipedi

**Comment by cscott** [comment]
It appears that much of this is generated by a body.js file included in the footer.  You might be able to replace (or 404!) that body.js file, then regenerate just the top-level hashes depending on that file.

**Comment by metasj** [comment]
I like that logo! 

How is this for the footer text:

> This page was generated and distributed by the Distributed Wikipedia project, from the article <TITLE/URL>, as of <DATE>. The text is available under a Creative Commons Attribution/Share Alike license. Media files are available under similar licenses; see the original file for details. The Distributed Wikipedia Project is not affiliated with the <LANGUAGE> Wikipedia.

**Comment by flyingzumwalt** [comment]
@cscott that covers the logo and the social media footer, but it doesn't cover the grey footer that includes "This article is issued from Vikipedi" -- shouldn't we also modify that footer? Maybe it's fine as long as the following footer clearly states that the page was disseminated by the Distributed Wikipedia project.

**Comment by flyingzumwalt** [comment]
@cscott @metasj FYI there's a working copy of these substitute assests in https://github.com/ipfs/distributed-wikipedia/pull/15

**Comment by ipfs-anon** [comment]
It appears that much of this is generated by a body.js file included in the footer.  You might be able to replace (or 404!) that body.js file, then regenerate just the top-level hashes depending on that file.

The logo, fb group, twitter id, etc. are all coming from a javascript file included at the bottom of every turkish wikipedia page. 
``` 
 .... <script src="../-/j/body.js"></script> ...
 ```
I suspect ZIM is adding this based on consolidating some javascript from the page at the time they crawled the page. This should be fairly easy to remove (and harmless since all it seems to be doing is add that footer which we want removed).

And, same for style.css file which contains the CSS for the header globe on the main page.
``` 
.globegris {
     background-image: url(../../I/s/Wikipedia-logo-v2-200px-transparent.png);
}
```

**Comment by flyingzumwalt** [comment]
Slightly tweaked footer text: 
> This page was generated and distributed by the Distributed Wikipedia Mirror project, from the article <TITLE/URL>, as of <>. For the most recent version of the article, see <>. The text is available under a Creative Commons Attribution/Share Alike license, by Wikipedia authors. Media files are available under similar licenses; see the original file for details. The Distributed Wikipedia Mirror is a global effort, independent from Wikipedia.

**Comment by jbenet** [comment]
Here is the source. It's a Pixelmator file. (not great). I will try to export every layer shortly.

[wikipedia-on-ipfs.pxm.zip](https://github.com/ipfs/distributed-wikipedia-mirror/files/980755/wikipedia-on-ipfs.pxm.zip)
