### ISSUE TITLE
Add English Snapshot

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#31]
_This is taking longer than the other languages because the english wikipedia dump is more than 20x bigger than the others._

Add Snapshot of http://en.wikipedia.org 

The IPNS entry for this snapshots will be  (we can update these links to point to the hash of the most recent snapshot) :
* English (en.wikipedia.org): https://ipfs.io/ipns/QmdJiuMWp2FxyaerfLrtdLF6Nr1EWpL7dPAxA9oKSPYYgV

When the corresponding snapshot is ready, we will update that IPNS entry to point to the snapshot. We will also announce the link to that snapshot in comments on this issue and on the ipfs blog.

**Comment by Kubuxu** [comment]
It took about 8h to decompress and add the English snapshot.

**Comment by zeta0134** [comment]
I noticed that the Turkish snapshot has a lovely search bar added to every page, but the English snapshot seems to lack this feature. I must assume that this is due to the gigantic size of the English snapshot, though I'm curious if there's some other technical roadblock causing trouble with the feature.

I'm not familiar enough with Wikipedia to know if there's an alternate way to see which pages are available; is there an index or tree built in somewhere that would enable browsing of page data? I mostly know the name of a given page I'd like to read in advance, or would be able to figure it out quickly if an index existed which allowed me to do a Ctrl+F on page titles.

**Comment by Kubuxu** [comment]
I have the search for English wiki almost done just not enough time to put it on.

**Comment by llopv** [comment]
You are heroes!

Can this issue be closed?

**Comment by flyingzumwalt** [comment]
Yes. I planned to put out a new post/tweet announcing the english snapshot but let's track that (and the need for search in the english snapshot) in a new issue.
