### ISSUE TITLE
Hackathon Wikimania 2017

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/distributed-wikipedia-mirror#41]
http://wiki.kiwix.org/wiki/Hackathon_Wikimania_2017

FYI In case anyone wants to go to this and hack on ipfs snapshots together with the kiwix people. (Kiwix is where we pull the snapshots from when we write them to IPFS)

What is it? Four full days of hacking Aug 14, 15, 16, 17 in Potsdam, NY, right after Wikipedia's annual conference in nearby Montreal (Wikimania 2017) towards the "offlining" aims outlined in http://wiki.kiwix.org/wiki/Hackathon_Wikimania_2017#Agenda!

**Comment by kelson42** [comment]
@flyingzumwalt 4 people of our team, mostly developers will be there, in particular at the hackathon during the pre-conference - and of course the offline hackathon after Wikimania. Would be great to see you there and discuss decentralised publication/distribution.

**Comment by flyingzumwalt** [comment]
@kelson42 I'm glad someone will be there who has been following this project.  I probably can't attend because I have other commitments that week.

Do you have any ideas how we can make the most of the hackathon? By then we should have a working version of the tooling discussed in #8 but that code, and especially the extraction runner(s) will probably need work.

**Comment by kelson42** [comment]
@flyingzumwalt 
I'm not sure if something can be really achieved during the hackathon which is useful for IPFS if nobody from IPFS is there. That said, I can only recommend to open tickets on Kiwix/openZIM Github projects if you need something specific from us.

Regarding #8, I want to say that:
* We have already a tool called zimdump (see in libzim repo) which does something similar like the custom tool you have built in rust. Maybe it's faster (it's c++) and does the job, this might make sense to benchmark it.
* I'm not super-convinced that extracting the content from the ZIM files to publish them afterwards is the coolest solution on the longer time. That's why I have open https://github.com/ipfs/distributed-wikipedia-mirror/issues/42 to try to figure out how much work is necessary to deliver ZIM files articles *directly* into the IPFS network. If that is doable, we might be able to help to implement it.

**Comment by kelson42** [comment]
@lidel Probably this could be closed.
