### ISSUE TITLE
Is there anyone is working on the version of Simplified Chinese?

### ISSUE THREAD

**Issue by jiweiqi** [ipfs/distributed-wikipedia-mirror#54]
Is there any plan?

**Comment by emuNAND** [comment]
i don't think anyone else is working on such a task, so i will try and do this myself
don't expect great reliability or always-on service though, my computer isn't that powerful
i will post the IPFS and IPNS hash here when i am finished

**Comment by kelson42** [comment]
@emuNAND At Kiwix, we create the ZIM files of Wikipedia which are at the source of this. I'm not so sure about the whole process, but we think Wikipedia over IPFS is a valuable service. If you want to provide a stable offer of Wikipedia over IPFS, we are interested to help.

**Comment by emuNAND** [comment]
@kelson42 
> we think Wikipedia over IPFS is a valuable service.
that's already been done, see [this file](https://github.com/ipfs/distributed-wikipedia-mirror/blob/master/snapshot-hashes.yml) for all the wikipedia mirrors the IPFS team has uploaded.
 > If you want to provide a stable offer of Wikipedia over IPFS, we are interested to help.
you might want to talk to @flyingzumwalt or other IPFS team members, i'm creating this mirror because it doesn't seem like anyone else wants to, as this issue has been open for 4 months.
if you mean you could provide me with a fully featured ZIM file or pin the hash i put up, i would greatly appreciate it. right now i am downloading the zh-nopic ZIM file from the website listed in the readme, and i dont have any other machine capable of hosting this much information other than my main computer, which i power off every day.

**Comment by emuNAND** [comment]
alright, a week later and i have managed to upload it to ipfs
here is the IPFS hash: [/ipfs/QmeXRmYjARbyUZshrFLszkUDEk7Ku4WQsdjRxF3QMMYtYy/](http://ipfs.io/ipfs/QmeXRmYjARbyUZshrFLszkUDEk7Ku4WQsdjRxF3QMMYtYy/)
im still trying to work out how to get the IPNS hash, as i am having problems with `ipfs files cp` and the script in the repo
hopefully for now this will work just as well for you
